formatter: markdown table

content: |-

  ## Usage
  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```
  
  {{ .Providers }}
  
  {{ .Modules }}
  
  {{ .Resources }}
  
  {{ .Inputs }}  
  
  {{ .Outputs }}

sort:
  enabled: true
  by: required

settings:
  anchor: false
  html: false
  escape: false
  hide-empty: true
  color: true